server:
  port: 2333

lavalink:
  server:
    password: "sagardc786@"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      http: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

logging:
  level:
    root: INFO
